export default function Head() {
  return (
    <>
      <title>Claire Lu</title>
      {/* <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" confused /> */}
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
